# Normalized Market Data Viewer

Inspect the normalized Parquet files produced by `modl-normalize`.

Defaults:
- root: `/mnt/burner-archive/ws_normalized`
- date: `2026-06-30`

Override with `MODL_WS_NORMALIZED_DIR` or `MODL_VIEW_DATE` before launching Jupyter.

In [1]:
from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path

import pandas as pd
import polars as pl

ROOT = Path(os.environ.get("MODL_WS_NORMALIZED_DIR", "/mnt/burner-archive/ws_normalized")).expanduser()
DATE = os.environ.get("MODL_VIEW_DATE", "2026-06-30")
DATE_TAG = datetime.strptime(DATE, "%Y-%m-%d").strftime("%y-%m-%d")

pd.set_option("display.max_columns", 160)
pd.set_option("display.max_colwidth", 180)
pl.Config.set_tbl_cols(160)
pl.Config.set_tbl_rows(20)

ROOT, DATE, DATE_TAG

(PosixPath('/mnt/burner-archive/ws_normalized'), '2026-06-30', '26-06-30')

In [2]:
def normalized_parts(path: Path, root: Path = ROOT) -> dict[str, str]:
    rel = path.relative_to(root)
    parts = rel.parts
    if len(parts) < 4:
        raise ValueError(f"unexpected normalized path shape: {path}")
    return {
        "exchange": parts[0],
        "symbol": parts[1],
        "dataset": parts[2],
        "file": parts[-1],
    }


def discover_files(root: Path = ROOT, date_tag: str = DATE_TAG) -> pd.DataFrame:
    rows = []
    for path in sorted(root.rglob(f"*_{date_tag}.parquet")):
        parts = normalized_parts(path, root)
        stat = path.stat()
        rows.append(
            {
                **parts,
                "key": f"{parts['exchange']}/{parts['symbol']}/{parts['dataset']}",
                "size_mb": round(stat.st_size / 1_000_000, 3),
                "path": str(path),
            }
        )
    return pd.DataFrame(rows)


files = discover_files()
files

,exchange,symbol,dataset,file,key,size_mb,path
0,bitfinex,tbtcusd,book_l25,tbtcusd_book_l25_26-06-30.parquet,bitfinex/tbtcusd/book_l25,1.543,/mnt/burner-archive/ws_normalized/bitfinex/tbtcusd/book_l25/tbtcusd_book_l25_26-06-30.parquet
1,bitfinex,tbtcusd,trades,tbtcusd_trades_26-06-30.parquet,bitfinex/tbtcusd/trades,0.075,/mnt/burner-archive/ws_normalized/bitfinex/tbtcusd/trades/tbtcusd_trades_26-06-30.parquet
2,deribit,btc,incremental_ticker,btc_incremental_ticker_26-06-30.parquet,deribit/btc/incremental_ticker,27.255,/mnt/burner-archive/ws_normalized/deribit/btc/incremental_ticker/btc_incremental_ticker_26-06-30.parquet
3,deribit,btc,instrument_state,btc_instrument_state_26-06-30.parquet,deribit/btc/instrument_state,0.063,/mnt/burner-archive/ws_normalized/deribit/btc/instrument_state/btc_instrument_state_26-06-30.parquet
4,deribit,btc,instruments,btc_instruments_26-06-30.parquet,deribit/btc/instruments,0.015,/mnt/burner-archive/ws_normalized/deribit/btc/instruments/btc_instruments_26-06-30.parquet
5,deribit,btc,trades,btc_trades_26-06-30.parquet,deribit/btc/trades,0.141,/mnt/burner-archive/ws_normalized/deribit/btc/trades/btc_trades_26-06-30.parquet
6,hibachi,btc_usdt-p,funding,btc_usdt-p_funding_26-06-30.parquet,hibachi/btc_usdt-p/funding,0.162,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/funding/btc_usdt-p_funding_26-06-30.parquet
7,hibachi,btc_usdt-p,orderbook,btc_usdt-p_orderbook_26-06-30.parquet,hibachi/btc_usdt-p/orderbook,1.151,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/orderbook/btc_usdt-p_orderbook_26-06-30.parquet
8,hibachi,btc_usdt-p,prices,btc_usdt-p_prices_26-06-30.parquet,hibachi/btc_usdt-p/prices,0.377,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/prices/btc_usdt-p_prices_26-06-30.parquet
9,hibachi,btc_usdt-p,quotes,btc_usdt-p_quotes_26-06-30.parquet,hibachi/btc_usdt-p/quotes,0.233,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/quotes/btc_usdt-p_quotes_26-06-30.parquet
10,hibachi,btc_usdt-p,trades,btc_usdt-p_trades_26-06-30.parquet,hibachi/btc_usdt-p/trades,0.013,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/trades/btc_usdt-p_trades_26-06-30.parquet
11,hyperliquid,ubtc_usdc,book,ubtc_usdc_book_26-06-30.parquet,hyperliquid/ubtc_usdc/book,0.180,/mnt/burner-archive/ws_normalized/hyperliquid/ubtc_usdc/book/ubtc_usdc_book_26-06-30.parquet
12,hyperliquid,ubtc_usdc,control,ubtc_usdc_control_26-06-30.parquet,hyperliquid/ubtc_usdc/control,0.005,/mnt/burner-archive/ws_normalized/hyperliquid/ubtc_usdc/control/ubtc_usdc_control_26-06-30.parquet
13,hyperliquid,ubtc_usdc,trades,ubtc_usdc_trades_26-06-30.parquet,hyperliquid/ubtc_usdc/trades,0.046,/mnt/burner-archive/ws_normalized/hyperliquid/ubtc_usdc/trades/ubtc_usdc_trades_26-06-30.parquet

In [3]:
if files.empty:
    raise FileNotFoundError(f"No normalized Parquet files found under {ROOT} for {DATE}")

DATASETS = dict(zip(files["key"], files["path"]))


def scan_dataset(key: str) -> pl.LazyFrame:
    return pl.scan_parquet(DATASETS[key])


def load_dataset(key: str, limit: int | None = None) -> pl.DataFrame:
    lf = scan_dataset(key)
    if limit is not None:
        lf = lf.head(limit)
    return lf.collect()


def row_count(key: str) -> int:
    return scan_dataset(key).select(pl.len().alias("rows")).collect().item()


summary = files[["exchange", "symbol", "dataset", "key", "size_mb", "path"]].copy()
summary["rows"] = [row_count(key) for key in summary["key"]]
summary.sort_values(["exchange", "symbol", "dataset"]).reset_index(drop=True)

,exchange,symbol,dataset,key,size_mb,path,rows
0,bitfinex,tbtcusd,book_l25,bitfinex/tbtcusd/book_l25,1.543,/mnt/burner-archive/ws_normalized/bitfinex/tbtcusd/book_l25/tbtcusd_book_l25_26-06-30.parquet,158343
1,bitfinex,tbtcusd,trades,bitfinex/tbtcusd/trades,0.075,/mnt/burner-archive/ws_normalized/bitfinex/tbtcusd/trades/tbtcusd_trades_26-06-30.parquet,4458
2,deribit,btc,incremental_ticker,deribit/btc/incremental_ticker,27.255,/mnt/burner-archive/ws_normalized/deribit/btc/incremental_ticker/btc_incremental_ticker_26-06-30.parquet,888043
3,deribit,btc,instrument_state,deribit/btc/instrument_state,0.063,/mnt/burner-archive/ws_normalized/deribit/btc/instrument_state/btc_instrument_state_26-06-30.parquet,4504
4,deribit,btc,instruments,deribit/btc/instruments,0.015,/mnt/burner-archive/ws_normalized/deribit/btc/instruments/btc_instruments_26-06-30.parquet,934
5,deribit,btc,trades,deribit/btc/trades,0.141,/mnt/burner-archive/ws_normalized/deribit/btc/trades/btc_trades_26-06-30.parquet,5252
6,hibachi,btc_usdt-p,funding,hibachi/btc_usdt-p/funding,0.162,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/funding/btc_usdt-p_funding_26-06-30.parquet,17170
7,hibachi,btc_usdt-p,orderbook,hibachi/btc_usdt-p/orderbook,1.151,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/orderbook/btc_usdt-p_orderbook_26-06-30.parquet,136117
8,hibachi,btc_usdt-p,prices,hibachi/btc_usdt-p/prices,0.377,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/prices/btc_usdt-p_prices_26-06-30.parquet,34340
9,hibachi,btc_usdt-p,quotes,hibachi/btc_usdt-p/quotes,0.233,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/quotes/btc_usdt-p_quotes_26-06-30.parquet,17170
10,hibachi,btc_usdt-p,trades,hibachi/btc_usdt-p/trades,0.013,/mnt/burner-archive/ws_normalized/hibachi/btc_usdt-p/trades/btc_usdt-p_trades_26-06-30.parquet,520
11,hyperliquid,ubtc_usdc,book,hyperliquid/ubtc_usdc/book,0.180,/mnt/burner-archive/ws_normalized/hyperliquid/ubtc_usdc/book/ubtc_usdc_book_26-06-30.parquet,40400
12,hyperliquid,ubtc_usdc,control,hyperliquid/ubtc_usdc/control,0.005,/mnt/burner-archive/ws_normalized/hyperliquid/ubtc_usdc/control/ubtc_usdc_control_26-06-30.parquet,34
13,hyperliquid,ubtc_usdc,trades,hyperliquid/ubtc_usdc/trades,0.046,/mnt/burner-archive/ws_normalized/hyperliquid/ubtc_usdc/trades/ubtc_usdc_trades_26-06-30.parquet,1111

## Pick A Dataset

Set `key` to any value from the summary table, then rerun the cells below.

In [4]:
sorted(DATASETS)

['bitfinex/tbtcusd/book_l25',
 'bitfinex/tbtcusd/trades',
 'deribit/btc/incremental_ticker',
 'deribit/btc/instrument_state',
 'deribit/btc/instruments',
 'deribit/btc/trades',
 'hibachi/btc_usdt-p/funding',
 'hibachi/btc_usdt-p/orderbook',
 'hibachi/btc_usdt-p/prices',
 'hibachi/btc_usdt-p/quotes',
 'hibachi/btc_usdt-p/trades',
 'hyperliquid/ubtc_usdc/book',
 'hyperliquid/ubtc_usdc/control',
 'hyperliquid/ubtc_usdc/trades']

In [14]:
key = "deribit/btc/instruments"
df = load_dataset(key)
df.head(20)

shape: (20, 21)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ exc ┆ sym ┆ ins ┆ kin ┆ sta ┆ bas ┆ quo ┆ set ┆ cou ┆ ins ┆ fut ┆ set ┆ opt ┆ pri ┆ str ┆ con ┆ tic ┆ exp ┆ cre ┆ ins ┆ is_ │
│ han ┆ bol ┆ tru ┆ d   ┆ te  ┆ e_c ┆ te_ ┆ tle ┆ nte ┆ tru ┆ ure ┆ tle ┆ ion ┆ ce_ ┆ ike ┆ tra ┆ k_s ┆ ira ┆ ati ┆ tru ┆ act │
│ ge  ┆ --- ┆ men ┆ --- ┆ --- ┆ urr ┆ cur ┆ men ┆ r_c ┆ men ┆ _ty ┆ men ┆ _ty ┆ ind ┆ --- ┆ ct_ ┆ ize ┆ tio ┆ on_ ┆ men ┆ ive │
│ --- ┆ str ┆ t_n ┆ str ┆ str ┆ enc ┆ ren ┆ t_c ┆ urr ┆ t_t ┆ pe  ┆ t_p ┆ pe  ┆ ex  ┆ str ┆ siz ┆ --- ┆ n_t ┆ tim ┆ t_i ┆ --- │
│ str ┆     ┆ ame ┆     ┆     ┆ y   ┆ cy  ┆ urr ┆ enc ┆ ype ┆ --- ┆ eri ┆ --- ┆ --- ┆     ┆ e   ┆ str ┆ ime ┆ est ┆ d   ┆ boo │
│     ┆     ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ enc ┆ y   ┆ --- ┆ str ┆ od  ┆ str ┆ str ┆     ┆ --- ┆     ┆ sta ┆ amp ┆ --- ┆ l   │
│     ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ --- ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆ mp  ┆ --- ┆ i64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ der ┆ btc ┆ BTC ┆ fut ┆ ope ┆ BTC ┆ USD ┆ BTC ┆ USD ┆ rev ┆ rev ┆ wee ┆ nul ┆ btc ┆ nul ┆ 10. ┆ 2.5 ┆ 178 ┆ 178 ┆ 648 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ure ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ ers ┆ k   ┆ l   ┆ _us ┆ l   ┆ 0   ┆     ┆ 367 ┆ 176 ┆ 483 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ ed  ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 961 ┆     ┆     │
│     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 4.8 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 651 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 236 ┆ 575 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 077 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 500 ┆     ┆     │
│     ┆     ┆ 480 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 4.8 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 651 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 236 ┆ 576 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 077 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 500 ┆     ┆     │
│     ┆     ┆ 480 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.0 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 650 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 219 ┆ 734 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 750 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.0 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 650 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 219 ┆ 735 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 750 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.2 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 649 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 181 ┆ 129 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 175 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 800 ┆     ┆     │
│     ┆     ┆ 520 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.2 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 649 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 181 ┆ 130 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 175 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 800 ┆     ┆     │
│     ┆     ┆ 520 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.4 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 649 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 181 ┆ 127 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 172 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 100 ┆     ┆     │
│     ┆     ┆ 540 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.4 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 649 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 181 ┆ 128 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 172 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 100 ┆     ┆     │
│     ┆     ┆ 540 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.5 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 648 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 176 ┆ 526 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 961 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 550 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.5 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 648 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 176 ┆ 527 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 961 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 550 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.6 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 649 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 179 ┆ 091 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 792 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆     ┆     │
│     ┆     ┆ 560 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.6 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 649 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 179 ┆ 092 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 792 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆     ┆     │
│     ┆     ┆ 560 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.7 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 652 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 239 ┆ 682 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 754 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 570 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.7 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 652 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 239 ┆ 683 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 754 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 570 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.8 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 648 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 176 ┆ 528 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 961 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 580 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.8 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 648 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 176 ┆ 529 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 961 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 580 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.9 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 651 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 232 ┆ 493 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 184 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆     ┆     │
│     ┆     ┆ 590 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.9 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 651 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 232 ┆ 494 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 184 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆     ┆     │
│     ┆     ┆ 590 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 6.0 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 648 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 176 ┆ 530 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 961 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 600 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [16]:
df_stats = df.describe()
df_stats

shape: (9, 22)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sta ┆ exc ┆ sym ┆ ins ┆ kin ┆ sta ┆ bas ┆ quo ┆ set ┆ cou ┆ ins ┆ fut ┆ set ┆ opt ┆ pri ┆ str ┆ con ┆ tic ┆ exp ┆ cre ┆ ins ┆ is_ │
│ tis ┆ han ┆ bol ┆ tru ┆ d   ┆ te  ┆ e_c ┆ te_ ┆ tle ┆ nte ┆ tru ┆ ure ┆ tle ┆ ion ┆ ce_ ┆ ike ┆ tra ┆ k_s ┆ ira ┆ ati ┆ tru ┆ act │
│ tic ┆ ge  ┆ --- ┆ men ┆ --- ┆ --- ┆ urr ┆ cur ┆ men ┆ r_c ┆ men ┆ _ty ┆ men ┆ _ty ┆ ind ┆ --- ┆ ct_ ┆ ize ┆ tio ┆ on_ ┆ men ┆ ive │
│ --- ┆ --- ┆ str ┆ t_n ┆ str ┆ str ┆ enc ┆ ren ┆ t_c ┆ urr ┆ t_t ┆ pe  ┆ t_p ┆ pe  ┆ ex  ┆ str ┆ siz ┆ --- ┆ n_t ┆ tim ┆ t_i ┆ --- │
│ str ┆ str ┆     ┆ ame ┆     ┆     ┆ y   ┆ cy  ┆ urr ┆ enc ┆ ype ┆ --- ┆ eri ┆ --- ┆ --- ┆     ┆ e   ┆ str ┆ ime ┆ est ┆ d   ┆ f64 │
│     ┆     ┆     ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ enc ┆ y   ┆ --- ┆ str ┆ od  ┆ str ┆ str ┆     ┆ --- ┆     ┆ sta ┆ amp ┆ --- ┆     │
│     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ --- ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆ mp  ┆ --- ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cou ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 14  ┆ 934 ┆ 920 ┆ 934 ┆ 920 ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 934 ┆ 934 │
│ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ .0  ┆ .0  ┆ .0  │
│ nul ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 920 ┆ 0   ┆ 14  ┆ 0   ┆ 14  ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ mea ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 1.8 ┆ 1.7 ┆ 621 ┆ 0.9 │
│ n   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 243 ┆ 767 ┆ 468 ┆ 507 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e12 ┆ e12 ┆ .59 ┆ 49  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 636 ┆     │
│ std ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 1.0 ┆ 1.0 ┆ 398 ┆ nul │
│     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 050 ┆ 455 ┆ 92. ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e12 ┆ e10 ┆ 844 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 571 ┆     │
│ min ┆ der ┆ btc ┆ BTC ┆ fut ┆ ina ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ rev ┆ day ┆ cal ┆ btc ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 1.7 ┆ 1.5 ┆ 210 ┆ 0.0 │
│     ┆ ibi ┆     ┆ -10 ┆ ure ┆ cti ┆     ┆     ┆     ┆     ┆ ers ┆ ers ┆     ┆ l   ┆ _us ┆ 2e+ ┆     ┆ 001 ┆ 828 ┆ 342 ┆ 838 ┆     │
│     ┆ t   ┆     ┆ JUL ┆     ┆ ve  ┆     ┆     ┆     ┆     ┆ ed  ┆ ed  ┆     ┆     ┆ d   ┆ 5   ┆     ┆     ┆ e12 ┆ e12 ┆ .0  ┆     │
│     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 25% ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 1.7 ┆ 1.7 ┆ 606 ┆ nul │
│     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 837 ┆ 745 ┆ 964 ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e12 ┆ e12 ┆ .0  ┆     │
│ 50% ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 1.7 ┆ 1.7 ┆ 638 ┆ nul │
│     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 879 ┆ 800 ┆ 395 ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e12 ┆ e12 ┆ .0  ┆     │
│ 75% ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 1.7 ┆ 1.7 ┆ 652 ┆ nul │
│     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 982 ┆ 824 ┆ 099 ┆ l   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e12 ┆ e12 ┆ .0  ┆     │
│ max ┆ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ USD ┆ BTC ┆ USD ┆ rev ┆ rev ┆ wee ┆ put ┆ btc ┆ 9.8 ┆ 10. ┆ 2.5 ┆ 3.2 ┆ 1.7 ┆ 654 ┆ 1.0 │
│     ┆ ibi ┆     ┆ -PE ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ ers ┆ k   ┆     ┆ _us ┆ e+4 ┆ 0   ┆     ┆ 504 ┆ 828 ┆ 669 ┆     │
│     ┆ t   ┆     ┆ RPE ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ ed  ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ e13 ┆ e12 ┆ .0  ┆     │
│     ┆     ┆     ┆ TUA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ L   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [17]:
df.schema

Schema([('exchange', String),
        ('symbol', String),
        ('instrument_name', String),
        ('kind', String),
        ('state', String),
        ('base_currency', String),
        ('quote_currency', String),
        ('settlement_currency', String),
        ('counter_currency', String),
        ('instrument_type', String),
        ('future_type', String),
        ('settlement_period', String),
        ('option_type', String),
        ('price_index', String),
        ('strike', String),
        ('contract_size', String),
        ('tick_size', String),
        ('expiration_timestamp', Int64),
        ('creation_timestamp', Int64),
        ('instrument_id', Int64),
        ('is_active', Boolean)])

## Lazy Stats Helper

`describe_dataset(key)` uses lazy scans and returns count/null/min/max/mean for numeric columns plus count/null/approx unique for string columns. This is safer for the bigger Deribit files than loading every table into memory.

In [18]:
NUMERIC_DTYPES = {
    pl.Int8,
    pl.Int16,
    pl.Int32,
    pl.Int64,
    pl.UInt8,
    pl.UInt16,
    pl.UInt32,
    pl.UInt64,
    pl.Float32,
    pl.Float64,
}


def describe_dataset(key: str) -> pl.DataFrame:
    lf = scan_dataset(key)
    schema = lf.collect_schema()
    exprs = [pl.len().alias("rows")]

    for name, dtype in schema.items():
        col = pl.col(name)
        exprs.append(col.null_count().alias(f"{name}__nulls"))
        if dtype in NUMERIC_DTYPES:
            exprs.extend(
                [
                    col.min().alias(f"{name}__min"),
                    col.max().alias(f"{name}__max"),
                    col.mean().alias(f"{name}__mean"),
                ]
            )
        elif dtype == pl.String:
            exprs.append(col.approx_n_unique().alias(f"{name}__approx_unique"))

    wide = lf.select(exprs).collect()
    rows = []
    for column in wide.columns:
        if column == "rows":
            rows.append({"column": "__table__", "metric": "rows", "value": wide[column][0]})
            continue
        name, metric = column.rsplit("__", 1)
        rows.append({"column": name, "metric": metric, "value": wide[column][0]})
    return pl.DataFrame(rows).sort(["column", "metric"])


describe_dataset(key)

shape: (48, 3)
┌────────────────────┬───────────────┬───────────┐
│ column             ┆ metric        ┆ value     │
│ ---                ┆ ---           ┆ ---       │
│ str                ┆ str           ┆ f64       │
╞════════════════════╪═══════════════╪═══════════╡
│ __table__          ┆ rows          ┆ 934.0     │
│ base_currency      ┆ approx_unique ┆ 1.0       │
│ base_currency      ┆ nulls         ┆ 0.0       │
│ contract_size      ┆ approx_unique ┆ 2.0       │
│ contract_size      ┆ nulls         ┆ 0.0       │
│ counter_currency   ┆ approx_unique ┆ 1.0       │
│ counter_currency   ┆ nulls         ┆ 0.0       │
│ creation_timestamp ┆ max           ┆ 1.7828e12 │
│ creation_timestamp ┆ mean          ┆ 1.7767e12 │
│ creation_timestamp ┆ min           ┆ 1.5342e12 │
│ …                  ┆ …             ┆ …         │
│ settlement_period  ┆ approx_unique ┆ 4.0       │
│ settlement_period  ┆ nulls         ┆ 0.0       │
│ state              ┆ approx_unique ┆ 2.0       │
│ state              ┆ nulls         ┆ 0.0       │
│ strike             ┆ approx_unique ┆ 94.0      │
│ strike             ┆ nulls         ┆ 14.0      │
│ symbol             ┆ approx_unique ┆ 1.0       │
│ symbol             ┆ nulls         ┆ 0.0       │
│ tick_size          ┆ approx_unique ┆ 3.0       │
│ tick_size          ┆ nulls         ┆ 0.0       │
└────────────────────┴───────────────┴───────────┘

## Preview Every Dataset

In [19]:
for dataset_key in sorted(DATASETS):
    print(f"\n{dataset_key}")
    display(load_dataset(dataset_key, limit=5))

bitfinex/tbtcusd/book_l25

shape: (5, 14)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬────────┬───────┬───────┬───────┬───────┬──────┐
│ exc ┆ sym ┆ rec ┆ rec ┆ con ┆ cha ┆ bit ┆ event_ ┆ level_ ┆ price ┆ count ┆ amoun ┆ amoun ┆ side │
│ han ┆ bol ┆ eiv ┆ eiv ┆ nec ┆ nne ┆ fin ┆ type   ┆ index  ┆ ---   ┆ ---   ┆ t     ┆ t_abs ┆ ---  │
│ ge  ┆ --- ┆ ed_ ┆ ed_ ┆ tio ┆ l   ┆ ex_ ┆ ---    ┆ ---    ┆ str   ┆ i64   ┆ ---   ┆ ---   ┆ str  │
│ --- ┆ str ┆ at  ┆ mts ┆ n_i ┆ --- ┆ cha ┆ str    ┆ i64    ┆       ┆       ┆ str   ┆ str   ┆      │
│ str ┆     ┆ --- ┆ --- ┆ d   ┆ str ┆ nne ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ str ┆ i64 ┆ --- ┆     ┆ l_i ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆     ┆     ┆ str ┆     ┆ d   ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪══════╡
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ boo ┆ 177 ┆ snapsh ┆ 0      ┆ 59881 ┆ 1     ┆ 0.002 ┆ 0.002 ┆ bid  │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ k_l ┆ 910 ┆ ot     ┆        ┆       ┆       ┆       ┆       ┆      │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆ 25  ┆ 2   ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 0T0 ┆ 659 ┆ tBT ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 3:2 ┆ 9   ┆ CUS ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 4:0 ┆     ┆ D-b ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 6.5 ┆     ┆ ook ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 99Z ┆     ┆ _l2 ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ boo ┆ 177 ┆ snapsh ┆ 1      ┆ 59879 ┆ 1     ┆ 0.074 ┆ 0.074 ┆ bid  │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ k_l ┆ 910 ┆ ot     ┆        ┆       ┆       ┆ 12797 ┆ 12797 ┆      │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆ 25  ┆ 2   ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 0T0 ┆ 659 ┆ tBT ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 3:2 ┆ 9   ┆ CUS ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 4:0 ┆     ┆ D-b ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 6.5 ┆     ┆ ook ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 99Z ┆     ┆ _l2 ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ boo ┆ 177 ┆ snapsh ┆ 2      ┆ 59874 ┆ 1     ┆ 0.083 ┆ 0.083 ┆ bid  │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ k_l ┆ 910 ┆ ot     ┆        ┆       ┆       ┆ 5074  ┆ 5074  ┆      │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆ 25  ┆ 2   ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 0T0 ┆ 659 ┆ tBT ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 3:2 ┆ 9   ┆ CUS ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 4:0 ┆     ┆ D-b ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 6.5 ┆     ┆ ook ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 99Z ┆     ┆ _l2 ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ boo ┆ 177 ┆ snapsh ┆ 3      ┆ 59873 ┆ 1     ┆ 0.083 ┆ 0.083 ┆ bid  │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ k_l ┆ 910 ┆ ot     ┆        ┆       ┆       ┆ 51009 ┆ 51009 ┆      │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆ 25  ┆ 2   ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 0T0 ┆ 659 ┆ tBT ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 3:2 ┆ 9   ┆ CUS ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 4:0 ┆     ┆ D-b ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 6.5 ┆     ┆ ook ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 99Z ┆     ┆ _l2 ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ boo ┆ 177 ┆ snapsh ┆ 4      ┆ 59872 ┆ 1     ┆ 0.077 ┆ 0.077 ┆ bid  │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ k_l ┆ 910 ┆ ot     ┆        ┆       ┆       ┆ 88546 ┆ 88546 ┆      │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆ 25  ┆ 2   ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 0T0 ┆ 659 ┆ tBT ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 3:2 ┆ 9   ┆ CUS ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 4:0 ┆     ┆ D-b ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 6.5 ┆     ┆ ook ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆ 99Z ┆     ┆ _l2 ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
│     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆        ┆        ┆       ┆       ┆       ┆       ┆      │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴────────┴───────┴───────┴───────┴───────┴──────┘

bitfinex/tbtcusd/trades

shape: (5, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬──────┬────────┬────────┬───────┐
│ exc ┆ sym ┆ rec ┆ rec ┆ con ┆ cha ┆ bit ┆ eve ┆ is_ ┆ tra ┆ tra ┆ side ┆ amount ┆ amount ┆ price │
│ han ┆ bol ┆ eiv ┆ eiv ┆ nec ┆ nne ┆ fin ┆ nt_ ┆ fin ┆ de_ ┆ de_ ┆ ---  ┆ ---    ┆ _abs   ┆ ---   │
│ ge  ┆ --- ┆ ed_ ┆ ed_ ┆ tio ┆ l   ┆ ex_ ┆ typ ┆ al  ┆ id  ┆ mts ┆ str  ┆ str    ┆ ---    ┆ str   │
│ --- ┆ str ┆ at  ┆ mts ┆ n_i ┆ --- ┆ cha ┆ e   ┆ --- ┆ --- ┆ --- ┆      ┆        ┆ str    ┆       │
│ str ┆     ┆ --- ┆ --- ┆ d   ┆ str ┆ nne ┆ --- ┆ boo ┆ i64 ┆ i64 ┆      ┆        ┆        ┆       │
│     ┆     ┆ str ┆ i64 ┆ --- ┆     ┆ l_i ┆ str ┆ l   ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆     ┆     ┆ str ┆     ┆ d   ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪══════╪════════╪════════╪═══════╡
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ tra ┆ 626 ┆ sna ┆ tru ┆ 194 ┆ 178 ┆ sell ┆ -0.000 ┆ 0.0002 ┆ 59896 │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ des ┆ 808 ┆ psh ┆ e   ┆ 271 ┆ 278 ┆      ┆ 2      ┆        ┆       │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆     ┆     ┆ ot  ┆     ┆ 760 ┆ 984 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 0T0 ┆ 476 ┆ tBT ┆     ┆     ┆     ┆     ┆ 2   ┆ 262 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 3:2 ┆ 1   ┆ CUS ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4:0 ┆     ┆ D-t ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4.7 ┆     ┆ rad ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 61Z ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ tra ┆ 626 ┆ sna ┆ tru ┆ 194 ┆ 178 ┆ sell ┆ -0.000 ┆ 0.0001 ┆ 59896 │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ des ┆ 808 ┆ psh ┆ e   ┆ 271 ┆ 278 ┆      ┆ 11092  ┆ 1092   ┆       │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆     ┆     ┆ ot  ┆     ┆ 760 ┆ 984 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 0T0 ┆ 476 ┆ tBT ┆     ┆     ┆     ┆     ┆ 1   ┆ 262 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 3:2 ┆ 1   ┆ CUS ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4:0 ┆     ┆ D-t ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4.7 ┆     ┆ rad ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 61Z ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ tra ┆ 626 ┆ sna ┆ tru ┆ 194 ┆ 178 ┆ sell ┆ -0.095 ┆ 0.0956 ┆ 59896 │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ des ┆ 808 ┆ psh ┆ e   ┆ 271 ┆ 278 ┆      ┆ 6      ┆        ┆       │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆     ┆     ┆ ot  ┆     ┆ 760 ┆ 984 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 0T0 ┆ 476 ┆ tBT ┆     ┆     ┆     ┆     ┆ 0   ┆ 262 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 3:2 ┆ 1   ┆ CUS ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4:0 ┆     ┆ D-t ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4.7 ┆     ┆ rad ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 61Z ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ tra ┆ 626 ┆ sna ┆ tru ┆ 194 ┆ 178 ┆ sell ┆ -0.104 ┆ 0.1044 ┆ 59896 │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ des ┆ 808 ┆ psh ┆ e   ┆ 271 ┆ 278 ┆      ┆ 4      ┆        ┆       │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆     ┆     ┆ ot  ┆     ┆ 759 ┆ 984 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 0T0 ┆ 476 ┆ tBT ┆     ┆     ┆     ┆     ┆ 7   ┆ 202 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 3:2 ┆ 1   ┆ CUS ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4:0 ┆     ┆ D-t ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4.7 ┆     ┆ rad ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 61Z ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│ bit ┆ tBT ┆ 202 ┆ 178 ┆ bit ┆ tra ┆ 626 ┆ sna ┆ tru ┆ 194 ┆ 178 ┆ sell ┆ -0.000 ┆ 0.0002 ┆ 59902 │
│ fin ┆ CUS ┆ 6-0 ┆ 278 ┆ fin ┆ des ┆ 808 ┆ psh ┆ e   ┆ 271 ┆ 278 ┆      ┆ 2      ┆        ┆       │
│ ex  ┆ D   ┆ 6-3 ┆ 984 ┆ ex- ┆     ┆     ┆ ot  ┆     ┆ 759 ┆ 984 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 0T0 ┆ 476 ┆ tBT ┆     ┆     ┆     ┆     ┆ 5   ┆ 142 ┆      ┆        ┆        ┆       │
│     ┆     ┆ 3:2 ┆ 1   ┆ CUS ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4:0 ┆     ┆ D-t ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 4.7 ┆     ┆ rad ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
│     ┆     ┆ 61Z ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆      ┆        ┆        ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴──────┴────────┴────────┴───────┘

deribit/btc/incremental_ticker

shape: (5, 45)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ exc ┆ sym ┆ rec ┆ rec ┆ con ┆ sub ┆ ins ┆ kin ┆ exp ┆ str ┆ opt ┆ set ┆ tic ┆ tic ┆ sta ┆ bes ┆ bes ┆ bes ┆ bes ┆ ind ┆ mar ┆ las ┆ und ┆ und ┆ ope ┆ set ┆ est ┆ min ┆ max ┆ bid ┆ ask ┆ mar ┆ fun ┆ cur ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ del ┆ gam ┆ the ┆ veg ┆ rho │
│ han ┆ bol ┆ eiv ┆ eiv ┆ nec ┆ scr ┆ tru ┆ d   ┆ ira ┆ ike ┆ ion ┆ tle ┆ ker ┆ ker ┆ te  ┆ t_b ┆ t_b ┆ t_a ┆ t_a ┆ ex_ ┆ k_p ┆ t_p ┆ erl ┆ erl ┆ n_i ┆ tle ┆ ima ┆ _pr ┆ _pr ┆ _iv ┆ _iv ┆ k_i ┆ din ┆ ren ┆ ts_ ┆ ts_ ┆ ts_ ┆ ts_ ┆ ts_ ┆ ts_ ┆ ta  ┆ ma  ┆ ta  ┆ a   ┆ --- │
│ ge  ┆ --- ┆ ed_ ┆ ed_ ┆ tio ┆ ipt ┆ men ┆ --- ┆ tio ┆ --- ┆ _ty ┆ men ┆ _ti ┆ _ty ┆ --- ┆ id_ ┆ id_ ┆ sk_ ┆ sk_ ┆ pri ┆ ric ┆ ric ┆ yin ┆ yin ┆ nte ┆ men ┆ ted ┆ ice ┆ ice ┆ --- ┆ --- ┆ v   ┆ g_8 ┆ t_f ┆ vol ┆ vol ┆ vol ┆ hig ┆ low ┆ pri ┆ --- ┆ --- ┆ --- ┆ --- ┆ str │
│ --- ┆ str ┆ at  ┆ mts ┆ n_i ┆ ion ┆ t_n ┆ str ┆ n_t ┆ str ┆ pe  ┆ t_p ┆ mes ┆ pe  ┆ str ┆ pri ┆ amo ┆ pri ┆ amo ┆ ce  ┆ e   ┆ e   ┆ g_p ┆ g_i ┆ res ┆ t_p ┆ _de ┆ --- ┆ --- ┆ str ┆ str ┆ --- ┆ h   ┆ und ┆ ume ┆ ume ┆ ume ┆ h   ┆ --- ┆ ce_ ┆ str ┆ str ┆ str ┆ str ┆     │
│ str ┆     ┆ --- ┆ --- ┆ d   ┆ _ch ┆ ame ┆     ┆ ime ┆     ┆ --- ┆ eri ┆ tam ┆ --- ┆     ┆ ce  ┆ unt ┆ ce  ┆ unt ┆ --- ┆ --- ┆ --- ┆ ric ┆ nde ┆ t   ┆ ric ┆ liv ┆ str ┆ str ┆     ┆     ┆ str ┆ --- ┆ ing ┆ --- ┆ _us ┆ _no ┆ --- ┆ str ┆ cha ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ str ┆ i64 ┆ --- ┆ ann ┆ --- ┆     ┆ sta ┆     ┆ str ┆ od  ┆ p   ┆ str ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ str ┆ str ┆ str ┆ e   ┆ x   ┆ --- ┆ e   ┆ ery ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ d   ┆ tio ┆ str ┆     ┆ nge ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ el  ┆ str ┆     ┆ mp  ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ str ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ _pr ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ nal ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ ice ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ inc ┆ BTC ┆ fut ┆ 325 ┆ nul ┆ nul ┆ per ┆ 178 ┆ sna ┆ ope ┆ 5.9 ┆ 6.0 ┆ 598 ┆ 217 ┆ 598 ┆ 598 ┆ 598 ┆ nul ┆ nul ┆ 855 ┆ 599 ┆ 598 ┆ 589 ┆ 607 ┆ nul ┆ nul ┆ nul ┆ 4.1 ┆ 0.0 ┆ 561 ┆ 336 ┆ 336 ┆ 607 ┆ 589 ┆ -0. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ rem ┆ -PE ┆ ure ┆ 037 ┆ l   ┆ l   ┆ pet ┆ 278 ┆ psh ┆ n   ┆ 8e+ ┆ e+4 ┆ 00. ┆ 790 ┆ 00. ┆ 03. ┆ 08. ┆ l   ┆ l   ┆ 923 ┆ 37. ┆ 00. ┆ 06. ┆ 01. ┆ l   ┆ l   ┆ l   ┆ 67e ┆     ┆ 1.1 ┆ 558 ┆ 558 ┆ 15. ┆ 36. ┆ 259 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ ent ┆ RPE ┆     ┆ 088 ┆     ┆     ┆ ual ┆ 984 ┆ ot  ┆     ┆ 4   ┆     ┆ 5   ┆ .0  ┆ 98  ┆ 53  ┆ 5   ┆     ┆     ┆ 310 ┆ 65  ┆ 98  ┆ 0   ┆ 0   ┆     ┆     ┆     ┆ -5  ┆     ┆ 060 ┆ 860 ┆ 860 ┆ 0   ┆ 0   ┆ 3   ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 647 ┆ TC- ┆ al_ ┆ TUA ┆     ┆ 000 ┆     ┆     ┆     ┆ 564 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 856 ┆ .0  ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 9   ┆ ins ┆ tic ┆ L   ┆     ┆ 00  ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ ker ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.4 ┆     ┆ men ┆ .BT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 79Z ┆     ┆ ts  ┆ C-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ERP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ETU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ inc ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ wee ┆ 178 ┆ sna ┆ ope ┆ 598 ┆ 751 ┆ 598 ┆ 352 ┆ 598 ┆ 598 ┆ 598 ┆ nul ┆ nul ┆ 132 ┆ 599 ┆ 598 ┆ 589 ┆ 607 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 171 ┆ 102 ┆ 102 ┆ 606 ┆ 589 ┆ -0. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ rem ┆ -3J ┆ ure ┆ 306 ┆ l   ┆ l   ┆ k   ┆ 278 ┆ psh ┆ n   ┆ 05. ┆ 0.0 ┆ 07. ┆ 0.0 ┆ 00. ┆ 14. ┆ 57. ┆ l   ┆ l   ┆ 660 ┆ 42. ┆ 00. ┆ 15. ┆ 12. ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ .40 ┆ 813 ┆ 813 ┆ 97. ┆ 32. ┆ 158 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ ent ┆ UL2 ┆     ┆ 560 ┆     ┆     ┆     ┆ 984 ┆ ot  ┆     ┆ 0   ┆     ┆ 5   ┆     ┆ 98  ┆ 0   ┆ 5   ┆     ┆     ┆ 30  ┆ 67  ┆ 98  ┆ 0   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆ 362 ┆ 90. ┆ 90. ┆ 5   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 648 ┆ TC- ┆ al_ ┆ 6   ┆     ┆ 000 ┆     ┆     ┆     ┆ 557 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 809 ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 4   ┆ ins ┆ tic ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ ker ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.4 ┆     ┆ men ┆ .BT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 84Z ┆     ┆ ts  ┆ C-3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ inc ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ mon ┆ 178 ┆ sna ┆ ope ┆ 599 ┆ 80. ┆ 599 ┆ 358 ┆ 598 ┆ 599 ┆ 599 ┆ nul ┆ nul ┆ 563 ┆ 600 ┆ 598 ┆ 590 ┆ 608 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 95. ┆ 576 ┆ 576 ┆ 608 ┆ 590 ┆ -0. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ rem ┆ -31 ┆ ure ┆ 548 ┆ l   ┆ l   ┆ th  ┆ 278 ┆ psh ┆ n   ┆ 22. ┆ 0   ┆ 25. ┆ 0.0 ┆ 00. ┆ 34. ┆ 20. ┆ l   ┆ l   ┆ 158 ┆ 40. ┆ 00. ┆ 35. ┆ 35. ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 835 ┆ 929 ┆ 929 ┆ 02. ┆ 52. ┆ 116 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ ent ┆ JUL ┆     ┆ 480 ┆     ┆     ┆     ┆ 984 ┆ ot  ┆     ┆ 5   ┆     ┆ 0   ┆     ┆ 98  ┆ 95  ┆ 0   ┆     ┆     ┆ 20  ┆ 98  ┆ 98  ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 392 ┆ 0.0 ┆ 0.0 ┆ 5   ┆ 5   ┆ 7   ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 648 ┆ TC- ┆ al_ ┆ 26  ┆     ┆ 000 ┆     ┆     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 4   ┆ ins ┆ tic ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ ker ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.4 ┆     ┆ men ┆ .BT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 84Z ┆     ┆ ts  ┆ C-3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 1JU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ L26 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ inc ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ day ┆ 178 ┆ sna ┆ ope ┆ 597 ┆ 187 ┆ 597 ┆ 187 ┆ 598 ┆ 597 ┆ 598 ┆ nul ┆ nul ┆ 126 ┆ 599 ┆ 598 ┆ 588 ┆ 606 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 7.0 ┆ 423 ┆ 423 ┆ 606 ┆ 589 ┆ -0. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ rem ┆ -30 ┆ ure ┆ 280 ┆ l   ┆ l   ┆     ┆ 278 ┆ psh ┆ n   ┆ 77. ┆ 0.0 ┆ 97. ┆ 0.0 ┆ 00. ┆ 92. ┆ 77. ┆ l   ┆ l   ┆ 336 ┆ 28. ┆ 00. ┆ 95. ┆ 90. ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 553 ┆ 520 ┆ 520 ┆ 47. ┆ 62. ┆ 087 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ ent ┆ JUN ┆     ┆ 640 ┆     ┆     ┆     ┆ 984 ┆ ot  ┆     ┆ 5   ┆     ┆ 5   ┆     ┆ 98  ┆ 39  ┆ 5   ┆     ┆     ┆ 0   ┆ 77  ┆ 98  ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 096 ┆ .0  ┆ .0  ┆ 5   ┆ 5   ┆ 6   ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 648 ┆ TC- ┆ al_ ┆ 26  ┆     ┆ 000 ┆     ┆     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 4   ┆ ins ┆ tic ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ ker ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.4 ┆     ┆ men ┆ .BT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 84Z ┆     ┆ ts  ┆ C-3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 0JU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ N26 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ inc ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ day ┆ 178 ┆ sna ┆ ope ┆ 597 ┆ 187 ┆ 598 ┆ 187 ┆ 598 ┆ 598 ┆ 598 ┆ nul ┆ nul ┆ 844 ┆ 599 ┆ 598 ┆ 589 ┆ 6.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 1.6 ┆ 102 ┆ 102 ┆ 605 ┆ 589 ┆ 0.1 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ rem ┆ -2J ┆ ure ┆ 297 ┆ l   ┆ l   ┆     ┆ 278 ┆ psh ┆ n   ┆ 92. ┆ 0.0 ┆ 12. ┆ 0.0 ┆ 00. ┆ 02. ┆ 97. ┆ l   ┆ l   ┆ 70  ┆ 35. ┆ 00. ┆ 02. ┆ 7e+ ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 981 ┆ 150 ┆ 150 ┆ 50. ┆ 70. ┆ 212 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ ent ┆ UL2 ┆     ┆ 920 ┆     ┆     ┆     ┆ 984 ┆ ot  ┆     ┆ 5   ┆     ┆ 5   ┆     ┆ 98  ┆ 0   ┆ 5   ┆     ┆     ┆     ┆ 19  ┆ 98  ┆ 5   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆ 680 ┆ .0  ┆ .0  ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 648 ┆ TC- ┆ al_ ┆ 6   ┆     ┆ 000 ┆     ┆     ┆     ┆ 563 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 4   ┆ ins ┆ tic ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ ker ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.4 ┆     ┆ men ┆ .BT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 84Z ┆     ┆ ts  ┆ C-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

deribit/btc/instrument_state

shape: (5, 11)
┌─────────┬────────┬─────────┬────────┬────────┬────────┬────────┬──────┬────────┬────────┬────────┐
│ exchang ┆ symbol ┆ receive ┆ receiv ┆ connec ┆ subscr ┆ instru ┆ kind ┆ timest ┆ state  ┆ raw_da │
│ e       ┆ ---    ┆ d_at    ┆ ed_mts ┆ tion_i ┆ iption ┆ ment_n ┆ ---  ┆ amp    ┆ ---    ┆ ta     │
│ ---     ┆ str    ┆ ---     ┆ ---    ┆ d      ┆ _chann ┆ ame    ┆ str  ┆ ---    ┆ str    ┆ ---    │
│ str     ┆        ┆ str     ┆ i64    ┆ ---    ┆ el     ┆ ---    ┆      ┆ i64    ┆        ┆ str    │
│         ┆        ┆         ┆        ┆ str    ┆ ---    ┆ str    ┆      ┆        ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆ str    ┆        ┆      ┆        ┆        ┆        │
╞═════════╪════════╪═════════╪════════╪════════╪════════╪════════╪══════╪════════╪════════╪════════╡
│ deribit ┆ BTC    ┆ 2026-06 ┆ 178280 ┆ deribi ┆ instru ┆ BTC-25 ┆ null ┆ 178280 ┆ settle ┆ {"inst │
│         ┆        ┆ -30T08: ┆ 640092 ┆ t-BTC- ┆ ment.s ┆ DEC26- ┆      ┆ 640084 ┆ ment   ┆ rument │
│         ┆        ┆ 00:00.9 ┆ 5      ┆ instru ┆ tate.o ┆ 85000- ┆      ┆ 0      ┆        ┆ _name" │
│         ┆        ┆ 25Z     ┆        ┆ ments  ┆ ption. ┆ P      ┆      ┆        ┆        ┆ :"BTC- │
│         ┆        ┆         ┆        ┆        ┆ BTC    ┆        ┆      ┆        ┆        ┆ 25DEC2 │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆      ┆        ┆        ┆ …      │
│ deribit ┆ BTC    ┆ 2026-06 ┆ 178280 ┆ deribi ┆ instru ┆ BTC-28 ┆ null ┆ 178280 ┆ settle ┆ {"inst │
│         ┆        ┆ -30T08: ┆ 640093 ┆ t-BTC- ┆ ment.s ┆ AUG26- ┆      ┆ 640084 ┆ ment   ┆ rument │
│         ┆        ┆ 00:00.9 ┆ 3      ┆ instru ┆ tate.o ┆ 94000- ┆      ┆ 0      ┆        ┆ _name" │
│         ┆        ┆ 33Z     ┆        ┆ ments  ┆ ption. ┆ P      ┆      ┆        ┆        ┆ :"BTC- │
│         ┆        ┆         ┆        ┆        ┆ BTC    ┆        ┆      ┆        ┆        ┆ 28AUG2 │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆      ┆        ┆        ┆ …      │
│ deribit ┆ BTC    ┆ 2026-06 ┆ 178280 ┆ deribi ┆ instru ┆ BTC-3J ┆ null ┆ 178280 ┆ settle ┆ {"inst │
│         ┆        ┆ -30T08: ┆ 640093 ┆ t-BTC- ┆ ment.s ┆ UL26-6 ┆      ┆ 640084 ┆ ment   ┆ rument │
│         ┆        ┆ 00:00.9 ┆ 4      ┆ instru ┆ tate.o ┆ 0500-C ┆      ┆ 0      ┆        ┆ _name" │
│         ┆        ┆ 34Z     ┆        ┆ ments  ┆ ption. ┆        ┆      ┆        ┆        ┆ :"BTC- │
│         ┆        ┆         ┆        ┆        ┆ BTC    ┆        ┆      ┆        ┆        ┆ 3JUL26 │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆      ┆        ┆        ┆ …      │
│ deribit ┆ BTC    ┆ 2026-06 ┆ 178280 ┆ deribi ┆ instru ┆ BTC-2J ┆ null ┆ 178280 ┆ settle ┆ {"inst │
│         ┆        ┆ -30T08: ┆ 640093 ┆ t-BTC- ┆ ment.s ┆ UL26-5 ┆      ┆ 640084 ┆ ment   ┆ rument │
│         ┆        ┆ 00:00.9 ┆ 4      ┆ instru ┆ tate.o ┆ 9000-C ┆      ┆ 0      ┆        ┆ _name" │
│         ┆        ┆ 34Z     ┆        ┆ ments  ┆ ption. ┆        ┆      ┆        ┆        ┆ :"BTC- │
│         ┆        ┆         ┆        ┆        ┆ BTC    ┆        ┆      ┆        ┆        ┆ 2JUL26 │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆      ┆        ┆        ┆ …      │
│ deribit ┆ BTC    ┆ 2026-06 ┆ 178280 ┆ deribi ┆ instru ┆ BTC-28 ┆ null ┆ 178280 ┆ settle ┆ {"inst │
│         ┆        ┆ -30T08: ┆ 640093 ┆ t-BTC- ┆ ment.s ┆ AUG26  ┆      ┆ 640084 ┆ ment   ┆ rument │
│         ┆        ┆ 00:00.9 ┆ 4      ┆ instru ┆ tate.f ┆        ┆      ┆ 1      ┆        ┆ _name" │
│         ┆        ┆ 34Z     ┆        ┆ ments  ┆ uture. ┆        ┆      ┆        ┆        ┆ :"BTC- │
│         ┆        ┆         ┆        ┆        ┆ BTC    ┆        ┆      ┆        ┆        ┆ 28AUG2 │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆      ┆        ┆        ┆ …      │
└─────────┴────────┴─────────┴────────┴────────┴────────┴────────┴──────┴────────┴────────┴────────┘

deribit/btc/instruments

shape: (5, 21)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ exc ┆ sym ┆ ins ┆ kin ┆ sta ┆ bas ┆ quo ┆ set ┆ cou ┆ ins ┆ fut ┆ set ┆ opt ┆ pri ┆ str ┆ con ┆ tic ┆ exp ┆ cre ┆ ins ┆ is_ │
│ han ┆ bol ┆ tru ┆ d   ┆ te  ┆ e_c ┆ te_ ┆ tle ┆ nte ┆ tru ┆ ure ┆ tle ┆ ion ┆ ce_ ┆ ike ┆ tra ┆ k_s ┆ ira ┆ ati ┆ tru ┆ act │
│ ge  ┆ --- ┆ men ┆ --- ┆ --- ┆ urr ┆ cur ┆ men ┆ r_c ┆ men ┆ _ty ┆ men ┆ _ty ┆ ind ┆ --- ┆ ct_ ┆ ize ┆ tio ┆ on_ ┆ men ┆ ive │
│ --- ┆ str ┆ t_n ┆ str ┆ str ┆ enc ┆ ren ┆ t_c ┆ urr ┆ t_t ┆ pe  ┆ t_p ┆ pe  ┆ ex  ┆ str ┆ siz ┆ --- ┆ n_t ┆ tim ┆ t_i ┆ --- │
│ str ┆     ┆ ame ┆     ┆     ┆ y   ┆ cy  ┆ urr ┆ enc ┆ ype ┆ --- ┆ eri ┆ --- ┆ --- ┆     ┆ e   ┆ str ┆ ime ┆ est ┆ d   ┆ boo │
│     ┆     ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ enc ┆ y   ┆ --- ┆ str ┆ od  ┆ str ┆ str ┆     ┆ --- ┆     ┆ sta ┆ amp ┆ --- ┆ l   │
│     ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ --- ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆ mp  ┆ --- ┆ i64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ der ┆ btc ┆ BTC ┆ fut ┆ ope ┆ BTC ┆ USD ┆ BTC ┆ USD ┆ rev ┆ rev ┆ wee ┆ nul ┆ btc ┆ nul ┆ 10. ┆ 2.5 ┆ 178 ┆ 178 ┆ 648 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ure ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ ers ┆ k   ┆ l   ┆ _us ┆ l   ┆ 0   ┆     ┆ 367 ┆ 176 ┆ 483 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ ed  ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 961 ┆     ┆     │
│     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 4.8 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 651 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 236 ┆ 575 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 077 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 500 ┆     ┆     │
│     ┆     ┆ 480 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 4.8 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 651 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 236 ┆ 576 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 077 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 500 ┆     ┆     │
│     ┆     ┆ 480 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ cal ┆ btc ┆ 5.0 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 650 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆ l   ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 219 ┆ 734 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 750 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ btc ┆ BTC ┆ opt ┆ ope ┆ BTC ┆ BTC ┆ BTC ┆ USD ┆ rev ┆ nul ┆ wee ┆ put ┆ btc ┆ 5.0 ┆ 1.0 ┆ 0.0 ┆ 178 ┆ 178 ┆ 650 ┆ tru │
│ ibi ┆     ┆ -10 ┆ ion ┆ n   ┆     ┆     ┆     ┆     ┆ ers ┆ l   ┆ k   ┆     ┆ _us ┆ e+4 ┆     ┆ 001 ┆ 367 ┆ 219 ┆ 735 ┆ e   │
│ t   ┆     ┆ JUL ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆ 040 ┆ 750 ┆     ┆     │
│     ┆     ┆ 26- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 200 ┆     ┆     │
│     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     │
│     ┆     ┆ 00- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

deribit/btc/trades

shape: (5, 28)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ exc ┆ sym ┆ rec ┆ rec ┆ con ┆ sub ┆ ins ┆ kin ┆ exp ┆ str ┆ opt ┆ set ┆ tra ┆ tra ┆ tra ┆ dir ┆ tic ┆ pri ┆ amo ┆ con ┆ mar ┆ ind ┆ iv  ┆ liq ┆ blo ┆ com ┆ com ┆ blo │
│ han ┆ bol ┆ eiv ┆ eiv ┆ nec ┆ scr ┆ tru ┆ d   ┆ ira ┆ ike ┆ ion ┆ tle ┆ de_ ┆ de_ ┆ de_ ┆ ect ┆ k_d ┆ ce  ┆ unt ┆ tra ┆ k_p ┆ ex_ ┆ --- ┆ uid ┆ ck_ ┆ bo_ ┆ bo_ ┆ ck_ │
│ ge  ┆ --- ┆ ed_ ┆ ed_ ┆ tio ┆ ipt ┆ men ┆ --- ┆ tio ┆ --- ┆ _ty ┆ men ┆ tim ┆ id  ┆ seq ┆ ion ┆ ire ┆ --- ┆ --- ┆ cts ┆ ric ┆ pri ┆ str ┆ ati ┆ tra ┆ id  ┆ tra ┆ rfq │
│ --- ┆ str ┆ at  ┆ mts ┆ n_i ┆ ion ┆ t_n ┆ str ┆ n_t ┆ str ┆ pe  ┆ t_p ┆ est ┆ --- ┆ --- ┆ --- ┆ cti ┆ str ┆ str ┆ --- ┆ e   ┆ ce  ┆     ┆ on  ┆ de_ ┆ --- ┆ de_ ┆ _id │
│ str ┆     ┆ --- ┆ --- ┆ d   ┆ _ch ┆ ame ┆     ┆ ime ┆     ┆ --- ┆ eri ┆ amp ┆ str ┆ i64 ┆ str ┆ on  ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ --- ┆ id  ┆ str ┆ id  ┆ --- │
│     ┆     ┆ str ┆ i64 ┆ --- ┆ ann ┆ --- ┆     ┆ sta ┆     ┆ str ┆ od  ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ --- ┆     ┆ --- ┆ i64 │
│     ┆     ┆     ┆     ┆ str ┆ el  ┆ str ┆     ┆ mp  ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ tra ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ mon ┆ 178 ┆ 436 ┆ 434 ┆ buy ┆ 2   ┆ 600 ┆ 299 ┆ 299 ┆ 600 ┆ 598 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ des ┆ -28 ┆ ure ┆ 790 ┆ l   ┆ l   ┆ th  ┆ 278 ┆ 192 ┆ 12  ┆     ┆     ┆ 67. ┆ 0.0 ┆ .0  ┆ 73. ┆ 00. ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ .BT ┆ AUG ┆     ┆ 400 ┆     ┆     ┆     ┆ 984 ┆ 446 ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆ 81  ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 648 ┆ TC- ┆ C-2 ┆ 26  ┆     ┆ 000 ┆     ┆     ┆     ┆ 571 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 7   ┆ ins ┆ 8AU ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ G26 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.4 ┆     ┆ men ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 87Z ┆     ┆ ts  ┆ 0ms ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ tra ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ mon ┆ 178 ┆ 436 ┆ 434 ┆ buy ┆ 3   ┆ 600 ┆ 630 ┆ 63. ┆ 600 ┆ 598 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ des ┆ -28 ┆ ure ┆ 790 ┆ l   ┆ l   ┆ th  ┆ 278 ┆ 192 ┆ 13  ┆     ┆     ┆ 67. ┆ .0  ┆ 0   ┆ 73. ┆ 00. ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ .BT ┆ AUG ┆     ┆ 400 ┆     ┆     ┆     ┆ 984 ┆ 447 ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆ 81  ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 649 ┆ TC- ┆ C-2 ┆ 26  ┆     ┆ 000 ┆     ┆     ┆     ┆ 593 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 0   ┆ ins ┆ 8AU ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ G26 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.4 ┆     ┆ men ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 90Z ┆     ┆ ts  ┆ 0ms ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ tra ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ mon ┆ 178 ┆ 436 ┆ 434 ┆ buy ┆ 3   ┆ 600 ┆ 299 ┆ 299 ┆ 600 ┆ 598 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ des ┆ -28 ┆ ure ┆ 790 ┆ l   ┆ l   ┆ th  ┆ 278 ┆ 192 ┆ 14  ┆     ┆     ┆ 67. ┆ 0.0 ┆ .0  ┆ 73. ┆ 00. ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ .BT ┆ AUG ┆     ┆ 400 ┆     ┆     ┆     ┆ 984 ┆ 448 ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆ 52  ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 649 ┆ TC- ┆ C-2 ┆ 26  ┆     ┆ 000 ┆     ┆     ┆     ┆ 617 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 0   ┆ ins ┆ 8AU ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ G26 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.4 ┆     ┆ men ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 90Z ┆     ┆ ts  ┆ 0ms ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ tra ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ mon ┆ 178 ┆ 436 ┆ 434 ┆ buy ┆ 0   ┆ 600 ┆ 362 ┆ 362 ┆ 600 ┆ 597 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ des ┆ -28 ┆ ure ┆ 790 ┆ l   ┆ l   ┆ th  ┆ 278 ┆ 192 ┆ 15  ┆     ┆     ┆ 72. ┆ 0.0 ┆ .0  ┆ 69. ┆ 97. ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ .BT ┆ AUG ┆     ┆ 400 ┆     ┆     ┆     ┆ 984 ┆ 449 ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆ 85  ┆ 31  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 697 ┆ TC- ┆ C-2 ┆ 26  ┆     ┆ 000 ┆     ┆     ┆     ┆ 660 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 4   ┆ ins ┆ 8AU ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ G26 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 6.9 ┆     ┆ men ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 74Z ┆     ┆ ts  ┆ 0ms ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ der ┆ BTC ┆ 202 ┆ 178 ┆ der ┆ tra ┆ BTC ┆ fut ┆ 178 ┆ nul ┆ nul ┆ mon ┆ 178 ┆ 436 ┆ 434 ┆ buy ┆ 1   ┆ 600 ┆ 362 ┆ 362 ┆ 600 ┆ 597 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ ibi ┆     ┆ 6-0 ┆ 278 ┆ ibi ┆ des ┆ -28 ┆ ure ┆ 790 ┆ l   ┆ l   ┆ th  ┆ 278 ┆ 192 ┆ 16  ┆     ┆     ┆ 72. ┆ 0.0 ┆ .0  ┆ 69. ┆ 97. ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ t   ┆     ┆ 6-3 ┆ 984 ┆ t-B ┆ .BT ┆ AUG ┆     ┆ 400 ┆     ┆     ┆     ┆ 984 ┆ 450 ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆ 94  ┆ 31  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 0T0 ┆ 730 ┆ TC- ┆ C-2 ┆ 26  ┆     ┆ 000 ┆     ┆     ┆     ┆ 705 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3:2 ┆ 3   ┆ ins ┆ 8AU ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4:0 ┆     ┆ tru ┆ G26 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 7.3 ┆     ┆ men ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 03Z ┆     ┆ ts  ┆ 0ms ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

hibachi/btc_usdt-p/funding

shape: (5, 8)
┌──────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ exchange ┆ symbol     ┆ received_a ┆ received_m ┆ connection ┆ channel   ┆ estimated ┆ next_fund │
│ ---      ┆ ---        ┆ t          ┆ ts         ┆ _id        ┆ ---       ┆ _funding_ ┆ ing_times │
│ str      ┆ str        ┆ ---        ┆ ---        ┆ ---        ┆ str       ┆ rate      ┆ tamp      │
│          ┆            ┆ str        ┆ i64        ┆ str        ┆           ┆ ---       ┆ ---       │
│          ┆            ┆            ┆            ┆            ┆           ┆ str       ┆ i64       │
╞══════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789845 ┆ hibachi-BT ┆ market_da ┆ 0.000037  ┆ 178279200 │
│          ┆            ┆ T03:24:05. ┆ 138        ┆ C/USDT-P-m ┆ ta        ┆           ┆ 0         │
│          ┆            ┆ 138Z       ┆            ┆ arket_data ┆           ┆           ┆           │
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789845 ┆ hibachi-BT ┆ market_da ┆ 0.000037  ┆ 178279200 │
│          ┆            ┆ T03:24:05. ┆ 428        ┆ C/USDT-P-m ┆ ta        ┆           ┆ 0         │
│          ┆            ┆ 428Z       ┆            ┆ arket_data ┆           ┆           ┆           │
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789845 ┆ hibachi-BT ┆ market_da ┆ 0.000037  ┆ 178279200 │
│          ┆            ┆ T03:24:05. ┆ 738        ┆ C/USDT-P-m ┆ ta        ┆           ┆ 0         │
│          ┆            ┆ 738Z       ┆            ┆ arket_data ┆           ┆           ┆           │
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789846 ┆ hibachi-BT ┆ market_da ┆ 0.000037  ┆ 178279200 │
│          ┆            ┆ T03:24:06. ┆ 036        ┆ C/USDT-P-m ┆ ta        ┆           ┆ 0         │
│          ┆            ┆ 036Z       ┆            ┆ arket_data ┆           ┆           ┆           │
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789846 ┆ hibachi-BT ┆ market_da ┆ 0.000037  ┆ 178279200 │
│          ┆            ┆ T03:24:06. ┆ 336        ┆ C/USDT-P-m ┆ ta        ┆           ┆ 0         │
│          ┆            ┆ 336Z       ┆            ┆ arket_data ┆           ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

hibachi/btc_usdt-p/orderbook

shape: (5, 16)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┐
│ exc ┆ sym ┆ rec ┆ rec ┆ con ┆ cha ┆ mes ┆ boo ┆ dep ┆ gra ┆ sid ┆ lev ┆ pri ┆ qua ┆ sta ┆ end_pr │
│ han ┆ bol ┆ eiv ┆ eiv ┆ nec ┆ nne ┆ sag ┆ k_t ┆ th  ┆ nul ┆ e   ┆ el_ ┆ ce  ┆ nti ┆ rt_ ┆ ice    │
│ ge  ┆ --- ┆ ed_ ┆ ed_ ┆ tio ┆ l   ┆ e_t ┆ ime ┆ --- ┆ ari ┆ --- ┆ ind ┆ --- ┆ ty  ┆ pri ┆ ---    │
│ --- ┆ str ┆ at  ┆ mts ┆ n_i ┆ --- ┆ ype ┆ sta ┆ i64 ┆ ty  ┆ str ┆ ex  ┆ str ┆ --- ┆ ce  ┆ str    │
│ str ┆     ┆ --- ┆ --- ┆ d   ┆ str ┆ --- ┆ mp_ ┆     ┆ --- ┆     ┆ --- ┆     ┆ str ┆ --- ┆        │
│     ┆     ┆ str ┆ i64 ┆ --- ┆     ┆ str ┆ ms  ┆     ┆ str ┆     ┆ i64 ┆     ┆     ┆ str ┆        │
│     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╡
│ hib ┆ BTC ┆ 202 ┆ 178 ┆ hib ┆ mar ┆ Sna ┆ 178 ┆ 20  ┆ 0.1 ┆ bid ┆ 0   ┆ 598 ┆ 0.0 ┆ 598 ┆ 59844. │
│ ach ┆ /US ┆ 6-0 ┆ 278 ┆ ach ┆ ket ┆ psh ┆ 278 ┆     ┆     ┆     ┆     ┆ 69. ┆ 008 ┆ 69. ┆ 8      │
│ i   ┆ DT- ┆ 6-3 ┆ 984 ┆ i-B ┆ _da ┆ ot  ┆ 984 ┆     ┆     ┆     ┆     ┆ 6   ┆ 346 ┆ 6   ┆        │
│     ┆ P   ┆ 0T0 ┆ 483 ┆ TC/ ┆ ta  ┆     ┆ 475 ┆     ┆     ┆     ┆     ┆     ┆ 249 ┆     ┆        │
│     ┆     ┆ 3:2 ┆ 2   ┆ USD ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4:0 ┆     ┆ T-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4.8 ┆     ┆ -ma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 32Z ┆     ┆ rke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ t_d ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ hib ┆ BTC ┆ 202 ┆ 178 ┆ hib ┆ mar ┆ Sna ┆ 178 ┆ 20  ┆ 0.1 ┆ bid ┆ 1   ┆ 598 ┆ 0.0 ┆ 598 ┆ 59844. │
│ ach ┆ /US ┆ 6-0 ┆ 278 ┆ ach ┆ ket ┆ psh ┆ 278 ┆     ┆     ┆     ┆     ┆ 67. ┆ 033 ┆ 69. ┆ 8      │
│ i   ┆ DT- ┆ 6-3 ┆ 984 ┆ i-B ┆ _da ┆ ot  ┆ 984 ┆     ┆     ┆     ┆     ┆ 0   ┆ 896 ┆ 6   ┆        │
│     ┆ P   ┆ 0T0 ┆ 483 ┆ TC/ ┆ ta  ┆     ┆ 475 ┆     ┆     ┆     ┆     ┆     ┆ 490 ┆     ┆        │
│     ┆     ┆ 3:2 ┆ 2   ┆ USD ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4:0 ┆     ┆ T-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4.8 ┆     ┆ -ma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 32Z ┆     ┆ rke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ t_d ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ hib ┆ BTC ┆ 202 ┆ 178 ┆ hib ┆ mar ┆ Sna ┆ 178 ┆ 20  ┆ 0.1 ┆ bid ┆ 2   ┆ 598 ┆ 0.0 ┆ 598 ┆ 59844. │
│ ach ┆ /US ┆ 6-0 ┆ 278 ┆ ach ┆ ket ┆ psh ┆ 278 ┆     ┆     ┆     ┆     ┆ 64. ┆ 250 ┆ 69. ┆ 8      │
│ i   ┆ DT- ┆ 6-3 ┆ 984 ┆ i-B ┆ _da ┆ ot  ┆ 984 ┆     ┆     ┆     ┆     ┆ 5   ┆ 533 ┆ 6   ┆        │
│     ┆ P   ┆ 0T0 ┆ 483 ┆ TC/ ┆ ta  ┆     ┆ 475 ┆     ┆     ┆     ┆     ┆     ┆ 652 ┆     ┆        │
│     ┆     ┆ 3:2 ┆ 2   ┆ USD ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4:0 ┆     ┆ T-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4.8 ┆     ┆ -ma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 32Z ┆     ┆ rke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ t_d ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ hib ┆ BTC ┆ 202 ┆ 178 ┆ hib ┆ mar ┆ Sna ┆ 178 ┆ 20  ┆ 0.1 ┆ bid ┆ 3   ┆ 598 ┆ 0.1 ┆ 598 ┆ 59844. │
│ ach ┆ /US ┆ 6-0 ┆ 278 ┆ ach ┆ ket ┆ psh ┆ 278 ┆     ┆     ┆     ┆     ┆ 62. ┆ 108 ┆ 69. ┆ 8      │
│ i   ┆ DT- ┆ 6-3 ┆ 984 ┆ i-B ┆ _da ┆ ot  ┆ 984 ┆     ┆     ┆     ┆     ┆ 3   ┆ 524 ┆ 6   ┆        │
│     ┆ P   ┆ 0T0 ┆ 483 ┆ TC/ ┆ ta  ┆     ┆ 475 ┆     ┆     ┆     ┆     ┆     ┆ 615 ┆     ┆        │
│     ┆     ┆ 3:2 ┆ 2   ┆ USD ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4:0 ┆     ┆ T-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4.8 ┆     ┆ -ma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 32Z ┆     ┆ rke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ t_d ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ hib ┆ BTC ┆ 202 ┆ 178 ┆ hib ┆ mar ┆ Sna ┆ 178 ┆ 20  ┆ 0.1 ┆ bid ┆ 4   ┆ 598 ┆ 0.0 ┆ 598 ┆ 59844. │
│ ach ┆ /US ┆ 6-0 ┆ 278 ┆ ach ┆ ket ┆ psh ┆ 278 ┆     ┆     ┆     ┆     ┆ 61. ┆ 002 ┆ 69. ┆ 8      │
│ i   ┆ DT- ┆ 6-3 ┆ 984 ┆ i-B ┆ _da ┆ ot  ┆ 984 ┆     ┆     ┆     ┆     ┆ 7   ┆ 336 ┆ 6   ┆        │
│     ┆ P   ┆ 0T0 ┆ 483 ┆ TC/ ┆ ta  ┆     ┆ 475 ┆     ┆     ┆     ┆     ┆     ┆ 950 ┆     ┆        │
│     ┆     ┆ 3:2 ┆ 2   ┆ USD ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4:0 ┆     ┆ T-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 4.8 ┆     ┆ -ma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆ 32Z ┆     ┆ rke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ t_d ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ ata ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┘

hibachi/btc_usdt-p/prices

shape: (5, 8)
┌──────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ exchange ┆ symbol     ┆ received_a ┆ received_m ┆ connection ┆ channel   ┆ price_typ ┆ price     │
│ ---      ┆ ---        ┆ t          ┆ ts         ┆ _id        ┆ ---       ┆ e         ┆ ---       │
│ str      ┆ str        ┆ ---        ┆ ---        ┆ ---        ┆ str       ┆ ---       ┆ str       │
│          ┆            ┆ str        ┆ i64        ┆ str        ┆           ┆ str       ┆           │
╞══════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789845 ┆ hibachi-BT ┆ market_da ┆ mark_pric ┆ 59862.602 │
│          ┆            ┆ T03:24:05. ┆ 138        ┆ C/USDT-P-m ┆ ta        ┆ e         ┆ 43        │
│          ┆            ┆ 138Z       ┆            ┆ arket_data ┆           ┆           ┆           │
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789845 ┆ hibachi-BT ┆ market_da ┆ spot_pric ┆ 59846.002 │
│          ┆            ┆ T03:24:05. ┆ 138        ┆ C/USDT-P-m ┆ ta        ┆ e         ┆ 15        │
│          ┆            ┆ 138Z       ┆            ┆ arket_data ┆           ┆           ┆           │
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789845 ┆ hibachi-BT ┆ market_da ┆ mark_pric ┆ 59862.602 │
│          ┆            ┆ T03:24:05. ┆ 428        ┆ C/USDT-P-m ┆ ta        ┆ e         ┆ 43        │
│          ┆            ┆ 428Z       ┆            ┆ arket_data ┆           ┆           ┆           │
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789845 ┆ hibachi-BT ┆ market_da ┆ spot_pric ┆ 59846.002 │
│          ┆            ┆ T03:24:05. ┆ 428        ┆ C/USDT-P-m ┆ ta        ┆ e         ┆ 15        │
│          ┆            ┆ 428Z       ┆            ┆ arket_data ┆           ┆           ┆           │
│ hibachi  ┆ BTC/USDT-P ┆ 2026-06-30 ┆ 1782789845 ┆ hibachi-BT ┆ market_da ┆ mark_pric ┆ 59862.131 │
│          ┆            ┆ T03:24:05. ┆ 738        ┆ C/USDT-P-m ┆ ta        ┆ e         ┆ 58        │
│          ┆            ┆ 738Z       ┆            ┆ arket_data ┆           ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

hibachi/btc_usdt-p/quotes

shape: (5, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ exchang ┆ symbol  ┆ receive ┆ receive ┆ connect ┆ channel ┆ bid_pri ┆ bid_siz ┆ ask_pri ┆ ask_si │
│ e       ┆ ---     ┆ d_at    ┆ d_mts   ┆ ion_id  ┆ ---     ┆ ce      ┆ e       ┆ ce      ┆ ze     │
│ ---     ┆ str     ┆ ---     ┆ ---     ┆ ---     ┆ str     ┆ ---     ┆ ---     ┆ ---     ┆ ---    │
│ str     ┆         ┆ str     ┆ i64     ┆ str     ┆         ┆ str     ┆ str     ┆ str     ┆ str    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ hibachi ┆ BTC/USD ┆ 2026-06 ┆ 1782789 ┆ hibachi ┆ market_ ┆ 59869.6 ┆ 0.00083 ┆ 59869.7 ┆ 0.0275 │
│         ┆ T-P     ┆ -30T03: ┆ 845138  ┆ -BTC/US ┆ data    ┆ 0000    ┆ 46249   ┆ 0000    ┆ 733826 │
│         ┆         ┆ 24:05.1 ┆         ┆ DT-P-ma ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆ 38Z     ┆         ┆ rket_da ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆         ┆         ┆ ta      ┆         ┆         ┆         ┆         ┆        │
│ hibachi ┆ BTC/USD ┆ 2026-06 ┆ 1782789 ┆ hibachi ┆ market_ ┆ 59861.7 ┆ 0.00023 ┆ 59864.2 ┆ 0.0275 │
│         ┆ T-P     ┆ -30T03: ┆ 845428  ┆ -BTC/US ┆ data    ┆ 0000    ┆ 36950   ┆ 0000    ┆ 733826 │
│         ┆         ┆ 24:05.4 ┆         ┆ DT-P-ma ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆ 28Z     ┆         ┆ rket_da ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆         ┆         ┆ ta      ┆         ┆         ┆         ┆         ┆        │
│ hibachi ┆ BTC/USD ┆ 2026-06 ┆ 1782789 ┆ hibachi ┆ market_ ┆ 59861.7 ┆ 0.00023 ┆ 59861.9 ┆ 0.0275 │
│         ┆ T-P     ┆ -30T03: ┆ 845738  ┆ -BTC/US ┆ data    ┆ 0000    ┆ 36950   ┆ 0000    ┆ 733826 │
│         ┆         ┆ 24:05.7 ┆         ┆ DT-P-ma ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆ 38Z     ┆         ┆ rket_da ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆         ┆         ┆ ta      ┆         ┆         ┆         ┆         ┆        │
│ hibachi ┆ BTC/USD ┆ 2026-06 ┆ 1782789 ┆ hibachi ┆ market_ ┆ 59861.7 ┆ 0.00023 ┆ 59861.9 ┆ 0.6624 │
│         ┆ T-P     ┆ -30T03: ┆ 846036  ┆ -BTC/US ┆ data    ┆ 0000    ┆ 36950   ┆ 0000    ┆ 242474 │
│         ┆         ┆ 24:06.0 ┆         ┆ DT-P-ma ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆ 36Z     ┆         ┆ rket_da ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆         ┆         ┆ ta      ┆         ┆         ┆         ┆         ┆        │
│ hibachi ┆ BTC/USD ┆ 2026-06 ┆ 1782789 ┆ hibachi ┆ market_ ┆ 59861.7 ┆ 0.00023 ┆ 59861.9 ┆ 0.6624 │
│         ┆ T-P     ┆ -30T03: ┆ 846336  ┆ -BTC/US ┆ data    ┆ 0000    ┆ 36950   ┆ 0000    ┆ 242474 │
│         ┆         ┆ 24:06.3 ┆         ┆ DT-P-ma ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆ 36Z     ┆         ┆ rket_da ┆         ┆         ┆         ┆         ┆        │
│         ┆         ┆         ┆         ┆ ta      ┆         ┆         ┆         ┆         ┆        │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

hibachi/btc_usdt-p/trades

shape: (5, 11)
┌────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ exchan ┆ symbol ┆ receiv ┆ receiv ┆ connec ┆ channe ┆ trade_ ┆ taker_ ┆ raw_ta ┆ price  ┆ quanti │
│ ge     ┆ ---    ┆ ed_at  ┆ ed_mts ┆ tion_i ┆ l      ┆ timest ┆ side   ┆ ker_si ┆ ---    ┆ ty     │
│ ---    ┆ str    ┆ ---    ┆ ---    ┆ d      ┆ ---    ┆ amp    ┆ ---    ┆ de     ┆ str    ┆ ---    │
│ str    ┆        ┆ str    ┆ i64    ┆ ---    ┆ str    ┆ ---    ┆ str    ┆ ---    ┆        ┆ str    │
│        ┆        ┆        ┆        ┆ str    ┆        ┆ i64    ┆        ┆ str    ┆        ┆        │
╞════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ hibach ┆ BTC/US ┆ 2026-0 ┆ 178278 ┆ hibach ┆ market ┆ 178278 ┆ sell   ┆ Sell   ┆ 59867. ┆ 0.0033 │
│ i      ┆ DT-P   ┆ 6-30T0 ┆ 984542 ┆ i-BTC/ ┆ _data  ┆ 9845   ┆        ┆        ┆ 00000  ┆ 896490 │
│        ┆        ┆ 3:24:0 ┆ 8      ┆ USDT-P ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆ 5.428Z ┆        ┆ -marke ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆        ┆        ┆ t_data ┆        ┆        ┆        ┆        ┆        ┆        │
│ hibach ┆ BTC/US ┆ 2026-0 ┆ 178278 ┆ hibach ┆ market ┆ 178278 ┆ sell   ┆ Sell   ┆ 59869. ┆ 0.0008 │
│ i      ┆ DT-P   ┆ 6-30T0 ┆ 984573 ┆ i-BTC/ ┆ _data  ┆ 9845   ┆        ┆        ┆ 60000  ┆ 346249 │
│        ┆        ┆ 3:24:0 ┆ 8      ┆ USDT-P ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆ 5.738Z ┆        ┆ -marke ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆        ┆        ┆ t_data ┆        ┆        ┆        ┆        ┆        ┆        │
│ hibach ┆ BTC/US ┆ 2026-0 ┆ 178278 ┆ hibach ┆ market ┆ 178278 ┆ sell   ┆ Sell   ┆ 59861. ┆ 0.0002 │
│ i      ┆ DT-P   ┆ 6-30T0 ┆ 984936 ┆ i-BTC/ ┆ _data  ┆ 9849   ┆        ┆        ┆ 70000  ┆ 336950 │
│        ┆        ┆ 3:24:0 ┆ 6      ┆ USDT-P ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆ 9.366Z ┆        ┆ -marke ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆        ┆        ┆ t_data ┆        ┆        ┆        ┆        ┆        ┆        │
│ hibach ┆ BTC/US ┆ 2026-0 ┆ 178279 ┆ hibach ┆ market ┆ 178279 ┆ buy    ┆ Buy    ┆ 59827. ┆ 0.0000 │
│ i      ┆ DT-P   ┆ 6-30T0 ┆ 000117 ┆ i-BTC/ ┆ _data  ┆ 0000   ┆        ┆        ┆ 60000  ┆ 258917 │
│        ┆        ┆ 3:26:4 ┆ 4      ┆ USDT-P ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆ 1.174Z ┆        ┆ -marke ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆        ┆        ┆ t_data ┆        ┆        ┆        ┆        ┆        ┆        │
│ hibach ┆ BTC/US ┆ 2026-0 ┆ 178279 ┆ hibach ┆ market ┆ 178279 ┆ sell   ┆ Sell   ┆ 59827. ┆ 0.0000 │
│ i      ┆ DT-P   ┆ 6-30T0 ┆ 000239 ┆ i-BTC/ ┆ _data  ┆ 0002   ┆        ┆        ┆ 50000  ┆ 215935 │
│        ┆        ┆ 3:26:4 ┆ 8      ┆ USDT-P ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆ 2.398Z ┆        ┆ -marke ┆        ┆        ┆        ┆        ┆        ┆        │
│        ┆        ┆        ┆        ┆ t_data ┆        ┆        ┆        ┆        ┆        ┆        │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

hyperliquid/ubtc_usdc/book

shape: (5, 14)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬────────┬──────┬───────┬───────┬───────┬───────┐
│ exc ┆ sym ┆ rec ┆ rec ┆ con ┆ cha ┆ coi ┆ book_t ┆ snapsh ┆ side ┆ level ┆ price ┆ size  ┆ order │
│ han ┆ bol ┆ eiv ┆ eiv ┆ nec ┆ nne ┆ n   ┆ imesta ┆ ot     ┆ ---  ┆ _inde ┆ ---   ┆ ---   ┆ _coun │
│ ge  ┆ --- ┆ ed_ ┆ ed_ ┆ tio ┆ l   ┆ --- ┆ mp     ┆ ---    ┆ str  ┆ x     ┆ str   ┆ str   ┆ t     │
│ --- ┆ str ┆ at  ┆ mts ┆ n_i ┆ --- ┆ str ┆ ---    ┆ bool   ┆      ┆ ---   ┆       ┆       ┆ ---   │
│ str ┆     ┆ --- ┆ --- ┆ d   ┆ str ┆     ┆ i64    ┆        ┆      ┆ i64   ┆       ┆       ┆ i64   │
│     ┆     ┆ str ┆ i64 ┆ --- ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆ str ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪════════╪══════╪═══════╪═══════╪═══════╪═══════╡
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ boo ┆ @14 ┆ 178278 ┆ false  ┆ bid  ┆ 0     ┆ 59808 ┆ 1.176 ┆ 4     │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ k   ┆ 2   ┆ 984466 ┆        ┆      ┆       ┆ .0    ┆ 16    ┆       │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆ 5      ┆        ┆      ┆       ┆       ┆       ┆       │
│ id  ┆     ┆ 0T0 ┆ 495 ┆ id- ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 53Z ┆     ┆     ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ boo ┆ @14 ┆ 178278 ┆ false  ┆ bid  ┆ 1     ┆ 59807 ┆ 0.186 ┆ 1     │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ k   ┆ 2   ┆ 984466 ┆        ┆      ┆       ┆ .0    ┆ 49    ┆       │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆ 5      ┆        ┆      ┆       ┆       ┆       ┆       │
│ id  ┆     ┆ 0T0 ┆ 495 ┆ id- ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 53Z ┆     ┆     ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ boo ┆ @14 ┆ 178278 ┆ false  ┆ bid  ┆ 2     ┆ 59805 ┆ 0.052 ┆ 1     │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ k   ┆ 2   ┆ 984466 ┆        ┆      ┆       ┆ .0    ┆ 01    ┆       │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆ 5      ┆        ┆      ┆       ┆       ┆       ┆       │
│ id  ┆     ┆ 0T0 ┆ 495 ┆ id- ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 53Z ┆     ┆     ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ boo ┆ @14 ┆ 178278 ┆ false  ┆ bid  ┆ 3     ┆ 59804 ┆ 0.046 ┆ 1     │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ k   ┆ 2   ┆ 984466 ┆        ┆      ┆       ┆ .0    ┆ 11    ┆       │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆ 5      ┆        ┆      ┆       ┆       ┆       ┆       │
│ id  ┆     ┆ 0T0 ┆ 495 ┆ id- ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 53Z ┆     ┆     ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ boo ┆ @14 ┆ 178278 ┆ false  ┆ bid  ┆ 4     ┆ 59803 ┆ 0.186 ┆ 1     │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ k   ┆ 2   ┆ 984466 ┆        ┆      ┆       ┆ .0    ┆ 51    ┆       │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆ 5      ┆        ┆      ┆       ┆       ┆       ┆       │
│ id  ┆     ┆ 0T0 ┆ 495 ┆ id- ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
│     ┆     ┆ 53Z ┆     ┆     ┆     ┆     ┆        ┆        ┆      ┆       ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴────────┴──────┴───────┴───────┴───────┴───────┘

hyperliquid/ubtc_usdc/control

shape: (5, 12)
┌────────┬────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┐
│ exchan ┆ symbol ┆ receiv ┆ receiv ┆ conne ┆ chann ┆ event ┆ messa ┆ metho ┆ subsc ┆ coin ┆ paylo │
│ ge     ┆ ---    ┆ ed_at  ┆ ed_mts ┆ ction ┆ el    ┆ ---   ┆ ge_ch ┆ d     ┆ ripti ┆ ---  ┆ ad_js │
│ ---    ┆ str    ┆ ---    ┆ ---    ┆ _id   ┆ ---   ┆ str   ┆ annel ┆ ---   ┆ on_ty ┆ str  ┆ on    │
│ str    ┆        ┆ str    ┆ i64    ┆ ---   ┆ str   ┆       ┆ ---   ┆ str   ┆ pe    ┆      ┆ ---   │
│        ┆        ┆        ┆        ┆ str   ┆       ┆       ┆ str   ┆       ┆ ---   ┆      ┆ str   │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆ str   ┆      ┆       │
╞════════╪════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╡
│ hyperl ┆ UBTC/U ┆ 2026-0 ┆ 178278 ┆ hyper ┆ contr ┆ conne ┆ null  ┆ null  ┆ null  ┆ null ┆ {"eve │
│ iquid  ┆ SDC    ┆ 6-30T0 ┆ 984481 ┆ liqui ┆ ol    ┆ cted  ┆       ┆       ┆       ┆      ┆ nt":" │
│        ┆        ┆ 3:24:0 ┆ 8      ┆ d-spo ┆       ┆       ┆       ┆       ┆       ┆      ┆ conne │
│        ┆        ┆ 4.818Z ┆        ┆ t-btc ┆       ┆       ┆       ┆       ┆       ┆      ┆ cted" │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ }     │
│ hyperl ┆ UBTC/U ┆ 2026-0 ┆ 178278 ┆ hyper ┆ contr ┆ null  ┆ subsc ┆ subsc ┆ trade ┆ @142 ┆ {"cha │
│ iquid  ┆ SDC    ┆ 6-30T0 ┆ 984494 ┆ liqui ┆ ol    ┆       ┆ ripti ┆ ribe  ┆ s     ┆      ┆ nnel" │
│        ┆        ┆ 3:24:0 ┆ 3      ┆ d-spo ┆       ┆       ┆ onRes ┆       ┆       ┆      ┆ :"sub │
│        ┆        ┆ 4.943Z ┆        ┆ t-btc ┆       ┆       ┆ ponse ┆       ┆       ┆      ┆ scrip │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ tionR │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ espon │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ …     │
│ hyperl ┆ UBTC/U ┆ 2026-0 ┆ 178278 ┆ hyper ┆ contr ┆ null  ┆ subsc ┆ subsc ┆ l2Boo ┆ @142 ┆ {"cha │
│ iquid  ┆ SDC    ┆ 6-30T0 ┆ 984495 ┆ liqui ┆ ol    ┆       ┆ ripti ┆ ribe  ┆ k     ┆      ┆ nnel" │
│        ┆        ┆ 3:24:0 ┆ 3      ┆ d-spo ┆       ┆       ┆ onRes ┆       ┆       ┆      ┆ :"sub │
│        ┆        ┆ 4.953Z ┆        ┆ t-btc ┆       ┆       ┆ ponse ┆       ┆       ┆      ┆ scrip │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ tionR │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ espon │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ …     │
│ hyperl ┆ UBTC/U ┆ 2026-0 ┆ 178279 ┆ hyper ┆ contr ┆ conne ┆ null  ┆ null  ┆ null  ┆ null ┆ {"eve │
│ iquid  ┆ SDC    ┆ 6-30T0 ┆ 517811 ┆ liqui ┆ ol    ┆ cted  ┆       ┆       ┆       ┆      ┆ nt":" │
│        ┆        ┆ 4:52:5 ┆ 2      ┆ d-spo ┆       ┆       ┆       ┆       ┆       ┆      ┆ conne │
│        ┆        ┆ 8.112Z ┆        ┆ t-btc ┆       ┆       ┆       ┆       ┆       ┆      ┆ cted" │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ }     │
│ hyperl ┆ UBTC/U ┆ 2026-0 ┆ 178279 ┆ hyper ┆ contr ┆ null  ┆ subsc ┆ subsc ┆ trade ┆ @142 ┆ {"cha │
│ iquid  ┆ SDC    ┆ 6-30T0 ┆ 517823 ┆ liqui ┆ ol    ┆       ┆ ripti ┆ ribe  ┆ s     ┆      ┆ nnel" │
│        ┆        ┆ 4:52:5 ┆ 5      ┆ d-spo ┆       ┆       ┆ onRes ┆       ┆       ┆      ┆ :"sub │
│        ┆        ┆ 8.235Z ┆        ┆ t-btc ┆       ┆       ┆ ponse ┆       ┆       ┆      ┆ scrip │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ tionR │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ espon │
│        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆ …     │
└────────┴────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┘

hyperliquid/ubtc_usdc/trades

shape: (5, 16)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┐
│ exc ┆ sym ┆ rec ┆ rec ┆ con ┆ cha ┆ coi ┆ sid ┆ raw ┆ pri ┆ siz ┆ tra ┆ has ┆ tra ┆ use ┆ user_1 │
│ han ┆ bol ┆ eiv ┆ eiv ┆ nec ┆ nne ┆ n   ┆ e   ┆ _si ┆ ce  ┆ e   ┆ de_ ┆ h   ┆ de_ ┆ r_0 ┆ ---    │
│ ge  ┆ --- ┆ ed_ ┆ ed_ ┆ tio ┆ l   ┆ --- ┆ --- ┆ de  ┆ --- ┆ --- ┆ tim ┆ --- ┆ id  ┆ --- ┆ str    │
│ --- ┆ str ┆ at  ┆ mts ┆ n_i ┆ --- ┆ str ┆ str ┆ --- ┆ str ┆ str ┆ est ┆ str ┆ --- ┆ str ┆        │
│ str ┆     ┆ --- ┆ --- ┆ d   ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ amp ┆     ┆ i64 ┆     ┆        │
│     ┆     ┆ str ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆        │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╡
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ tra ┆ @14 ┆ buy ┆ B   ┆ 599 ┆ 0.0 ┆ 178 ┆ 0x0 ┆ 656 ┆ 0xc ┆ 0xf910 │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ des ┆ 2   ┆     ┆     ┆ 21. ┆ 036 ┆ 278 ┆ f0c ┆ 384 ┆ 01b ┆ 9ada2f │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆     ┆     ┆ 0   ┆ 1   ┆ 969 ┆ 30b ┆ 212 ┆ 675 ┆ 73c62e │
│ id  ┆     ┆ 0T0 ┆ 494 ┆ id- ┆     ┆     ┆     ┆     ┆     ┆     ┆ 351 ┆ f6c ┆ 498 ┆ 082 ┆ 9889b4 │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ c61 ┆ 998 ┆ 100 ┆ 545306 │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8ff ┆     ┆ 702 ┆ …      │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 108 ┆     ┆ 46b ┆        │
│     ┆     ┆ 43Z ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 504 ┆     ┆ af0 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3ed ┆     ┆ 0ad ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e1c ┆     ┆ f32 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆        │
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ tra ┆ @14 ┆ buy ┆ B   ┆ 599 ┆ 0.0 ┆ 178 ┆ 0x0 ┆ 324 ┆ 0x8 ┆ 0x1c1c │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ des ┆ 2   ┆     ┆     ┆ 17. ┆ 003 ┆ 278 ┆ 000 ┆ 292 ┆ 0a6 ┆ 270b57 │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆     ┆     ┆ 0   ┆ 5   ┆ 969 ┆ 000 ┆ 006 ┆ b9c ┆ 3d55b6 │
│ id  ┆     ┆ 0T0 ┆ 494 ┆ id- ┆     ┆     ┆     ┆     ┆     ┆     ┆ 700 ┆ 000 ┆ 561 ┆ e00 ┆ 8b3d14 │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 000 ┆ 002 ┆ 633 ┆ 722b5d │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 1f2 ┆ …      │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ bea ┆        │
│     ┆     ┆ 43Z ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 019 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 90f ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 731 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆        │
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ tra ┆ @14 ┆ sel ┆ A   ┆ 599 ┆ 0.0 ┆ 178 ┆ 0x0 ┆ 290 ┆ 0x3 ┆ 0x28f0 │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ des ┆ 2   ┆ l   ┆     ┆ 14. ┆ 002 ┆ 278 ┆ 000 ┆ 000 ┆ 999 ┆ 233472 │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 970 ┆ 000 ┆ 434 ┆ 65e ┆ b6a44e │
│ id  ┆     ┆ 0T0 ┆ 494 ┆ id- ┆     ┆     ┆     ┆     ┆     ┆     ┆ 200 ┆ 000 ┆ 457 ┆ 15d ┆ 170e00 │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ 000 ┆ 937 ┆ 4e6 ┆ 2a7284 │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 1ec ┆ …      │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 352 ┆        │
│     ┆     ┆ 43Z ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 9cc ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 98b ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 7f7 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆        │
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ tra ┆ @14 ┆ buy ┆ B   ┆ 599 ┆ 0.0 ┆ 178 ┆ 0x0 ┆ 191 ┆ 0x8 ┆ 0x1c1c │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ des ┆ 2   ┆     ┆     ┆ 06. ┆ 003 ┆ 278 ┆ 000 ┆ 183 ┆ 0a6 ┆ 270b57 │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆     ┆     ┆ 0   ┆ 5   ┆ 970 ┆ 000 ┆ 443 ┆ b9c ┆ 3d55b6 │
│ id  ┆     ┆ 0T0 ┆ 494 ┆ id- ┆     ┆     ┆     ┆     ┆     ┆     ┆ 401 ┆ 000 ┆ 988 ┆ e00 ┆ 8b3d14 │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 000 ┆ 514 ┆ 633 ┆ 722b5d │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 1f2 ┆ …      │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ bea ┆        │
│     ┆     ┆ 43Z ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 019 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 90f ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 731 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆        │
│ hyp ┆ UBT ┆ 202 ┆ 178 ┆ hyp ┆ tra ┆ @14 ┆ sel ┆ A   ┆ 598 ┆ 0.0 ┆ 178 ┆ 0x0 ┆ 979 ┆ 0x9 ┆ 0xf036 │
│ erl ┆ C/U ┆ 6-0 ┆ 278 ┆ erl ┆ des ┆ 2   ┆ l   ┆     ┆ 99. ┆ 015 ┆ 278 ┆ 000 ┆ 122 ┆ 266 ┆ a52614 │
│ iqu ┆ SDC ┆ 6-3 ┆ 984 ┆ iqu ┆     ┆     ┆     ┆     ┆ 0   ┆ 5   ┆ 972 ┆ 000 ┆ 725 ┆ 865 ┆ 06a394 │
│ id  ┆     ┆ 0T0 ┆ 494 ┆ id- ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ 000 ┆ 840 ┆ bb6 ┆ bd63eb │
│     ┆     ┆ 3:2 ┆ 3   ┆ spo ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 000 ┆ 501 ┆ afb ┆ 4df49c │
│     ┆     ┆ 4:0 ┆     ┆ t-b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 4c4 ┆ …      │
│     ┆     ┆ 4.9 ┆     ┆ tc  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ f61 ┆        │
│     ┆     ┆ 43Z ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 854 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 4dd ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆ 3b8 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆        │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┘

## Common Feature Inputs

In [20]:
trade_keys = [key for key in sorted(DATASETS) if key.endswith("/trades")]
book_keys = [key for key in sorted(DATASETS) if key.endswith("/book") or key.endswith("/book_l25") or key.endswith("/orderbook")]
price_keys = [key for key in sorted(DATASETS) if key.endswith("/prices") or key.endswith("/quotes") or key.endswith("/incremental_ticker")]

trade_keys, book_keys, price_keys

(['bitfinex/tbtcusd/trades',
  'deribit/btc/trades',
  'hibachi/btc_usdt-p/trades',
  'hyperliquid/ubtc_usdc/trades'],
 ['bitfinex/tbtcusd/book_l25',
  'hibachi/btc_usdt-p/orderbook',
  'hyperliquid/ubtc_usdc/book'],
 ['deribit/btc/incremental_ticker',
  'hibachi/btc_usdt-p/prices',
  'hibachi/btc_usdt-p/quotes'])

In [21]:
# Canonical Bitfinex trades only. This avoids double-counting te/tu pairs.
if "bitfinex/tbtcusd/trades" in DATASETS:
    bitfinex_final_trades = (
        scan_dataset("bitfinex/tbtcusd/trades")
        .filter(pl.col("is_final"))
        .select(["received_at", "trade_mts", "side", "amount_abs", "price", "event_type", "is_final"])
        .head(20)
        .collect()
    )
    bitfinex_final_trades
else:
    print("bitfinex/tbtcusd/trades not found")

In [22]:
# Quick row-count summary by venue.
summary_by_exchange = (
    pl.from_pandas(summary)
    .group_by("exchange")
    .agg([
        pl.len().alias("datasets"),
        pl.col("rows").sum().alias("rows"),
        pl.col("size_mb").sum().round(3).alias("size_mb"),
    ])
    .sort("exchange")
)
summary_by_exchange

shape: (4, 4)
┌─────────────┬──────────┬────────┬─────────┐
│ exchange    ┆ datasets ┆ rows   ┆ size_mb │
│ ---         ┆ ---      ┆ ---    ┆ ---     │
│ str         ┆ u32      ┆ i64    ┆ f64     │
╞═════════════╪══════════╪════════╪═════════╡
│ bitfinex    ┆ 2        ┆ 162801 ┆ 1.618   │
│ deribit     ┆ 4        ┆ 898733 ┆ 27.474  │
│ hibachi     ┆ 5        ┆ 205317 ┆ 1.936   │
│ hyperliquid ┆ 3        ┆ 41545  ┆ 0.231   │
└─────────────┴──────────┴────────┴─────────┘